name: Build Flutter Android

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'

      # 3️⃣ Setup Java (required for Android SDK)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: '34.0.0'
          ndk: '21.4.7075529'
          target: default

      # 5️⃣ Get Flutter dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 6️⃣ Generate launcher icons (مهم)
      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons:main

      # 7️⃣ Build APK
      - name: Build APK
        run: flutter build apk --release

      # 8️⃣ Build AAB
      - name: Build App Bundle
        run: flutter build appbundle --release

      # 9️⃣ Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
